### ISSUE TITLE
Ubuntu install script is outdated

### ISSUE THREAD

**Issue by mgmacias95** [sonofagl1tch/AWSDetonationLab#17]
Hello @sonofagl1tch,

I've noticed the script in `/additionalInstallationScripts/installWazuh-Ubuntu.sh` is outdated respecting to the installWazuh script used for Amazon Linux. 

I think it would be a good idea to make some kind of library with common install functions for both rpm and deb. The only difference between the two should be the way repositories are managed.

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
I marked this issue as "help wanted" because I have never created a library with common install functions for both rpm and deb. I am hoping someone else can help with that.

**Comment by mgmacias95** [comment]
@BraulioV can help us with that 😄 .

**Comment by sonofagl1tch** [comment]
completed with https://github.com/sonofagl1tch/AWSDetonationLab/pull/67
