### ISSUE TITLE
Agents are not automatically registered

### ISSUE THREAD

**Issue by mgmacias95** [sonofagl1tch/AWSDetonationLab#3]
Hi @sonofagl1tch,

After deploying the detonation lab, I had to register the agents manually. I think the registration scripts should be improved to use [authd](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html).

Currently defined tasks:
* [x] Add port 1515 to wazuh manager's security group (the wazuh agent doesnt need to have any opened port).
* [x] Enable `authd` in the wazuh manager.
* [x] Modify registration script for linux agents.
* [x] Modify registration script for windows agents using the MSI (https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html#using-the-command-line).

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
I can update the security group easily but can yo elaborate on "Enable authd in the wazuh manager."? In order to do this I need to figure out what file this configuration exists in so i can manually modify it during the installation of the server.

**Comment by mgmacias95** [comment]
Hi @sonofagl1tch,

`authd` is a service Wazuh has for agent registration ([docs](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#register-the-agent)).

To enable it use the following command:
```
# /var/ossec/bin/ossec-control enable auth
```

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
current status is that the linux client automatically connects via the new authd method but the windows client is not yet working with the new method. needs further troubleshooting

**Comment by mgmacias95** [comment]
Current status:
```
Warning: Permanently added '172.16.0.21' (ECDSA) to the list of known hosts.

       __|  __|_  )
       _|  (     /   Amazon Linux 2 AMI
      ___|\___|___|

https://aws.amazon.com/amazon-linux-2/
No packages needed for security; 3 packages available
Run "sudo yum update" to apply all updates.
[ec2-user@ip-172-16-0-21 ~]$ sudo su
[root@ip-172-16-0-21 ec2-user]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-16-0-21.ec2.internal (server), IP: 127.0.0.1, Active/Local
   ID: 001, Name: windowsVictim, IP: 172.16.0.23, Active
   ID: 002, Name: linuxVictim, IP: 172.16.0.22, Active

List of agentless devices:
```

All agents are correctly registered when the template is deployed :).
