### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by rossw7** [sonofagl1tch/AWSDetonationLab#36]
Some Resources are named firehose and some are named firehost

firehostdeliveryRoleGuardDuty
firehostdeliveryRoleIAM
firehostdeliveryRoleInspector
firehostdeliveryRoleMacie
firehostdeliveryRoleVPC

**Comment by sonofagl1tch** [comment]
Thank you for catching that! I have a pull request #37 to fix this waiting on review
