### ISSUE TITLE
Add support for AWS Trust Advisor

### ISSUE THREAD

**Issue by mgmacias95** [sonofagl1tch/AWSDetonationLab#50]
Hello @sonofagl1tch,

The Wazuh team has added support for AWS Trust Advisor in https://github.com/wazuh/wazuh/pull/1845. I think we should add it to the detonation lab. 

Tasks:
- [ ] Enable service in CF template.
- [ ] Create bucket and forward AWS Trust Advisor events to the bucket.
- [ ] Add necessary configuration to `ossec.conf` file in Wazuh manager.

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
trusted advisor does not provide significant value in the detlab at this time by the nature of the detlab being a short term infrastructure inside a private vpc.
