### ISSUE TITLE
Add a low cost template

### ISSUE THREAD

**Issue by mgmacias95** [sonofagl1tch/AWSDetonationLab#8]
**Is your feature request related to a problem? Please describe.**
The actual template deploys very expensive EC2 instances. I think the deployed environment is good for production but it's too much for someone who only wants to do a few testing or playing around.

**Describe the solution you'd like**
Add another template, this way the user would have two options to chose from: prod or testing.
I don't want to do it by copying and pasting, if the code of one template can't be used for the other we can try doing a script that generates the template or something like that.

**Comment by sonofagl1tch** [comment]
look for the field "InstanceType" to see what size the instance is going to be
