### ISSUE TITLE
Create a Wiki using README's information

### ISSUE THREAD

**Issue by mgmacias95** [sonofagl1tch/AWSDetonationLab#9]
Hi @sonofagl1tch,

I think the README is too long. It's difficult to find specific information and it's necessary to do a lot of scrolling to get to the _Get Started_ section.

It would be much better to have all that information organized in a Wiki section. I think the following the Wiki can have the following sections:
* [x] Environment deployed by the template (topology, what does the template do, things that cannot go inside the template and why...).
* [x] Installing the template.
* [x] Configuring/Accessing remotely (Windows, Mac and Linux).
* [x] Configuring Wazuh.

Best regards,
Marta

**Comment by sonofagl1tch** [comment]
ReadME migrated to github wiki and redirection link added to readME page
